modLoader="javafml"
loaderVersion="[60.1,)"
license="MIT"

[[mods]]
modId="smart_particles"
version="1.21.10"
displayName="Smart Particles"
authors="Andrew-Chedid"
description="A performance mod that caps the total particle count."
logoFile="assets/icon.png"

[[dependencies.smart_particles]]
modId="forge"
mandatory=true
versionRange="[60.1.0,60.1.1)"
ordering="NONE"
side="BOTH"

[[dependencies.smart_particles]]
modId="minecraft"
mandatory=true
versionRange="[1.21.10, 1.21.11)"
ordering="NONE"
side="BOTH"